# Generated by Django 6.0.1 on 2026-03-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='hostel_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
