# Generated by Django 6.0.1 on 2026-03-07 15:31

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('hostelapp', '0003_delete_professional'), ('hostelapp', '0004_remove_professional_model')]

    dependencies = [
        ('hostelapp', '0002_complaint_complaint_type_complaint_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Professional',
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Professional',
                ),
            ],
        ),
    ]
