# Generated by Django 6.0.1 on 2026-03-06 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0002_complaint_complaint_type_complaint_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Professional',
        ),
    ]
